### PR TITLE
Update support libraries 24.2.0

### PR DESCRIPTION
**Pull request by jaredsburrows**
@JakeWharton 
- Updated android gradle plugin 2.1.3(didn't see this before)
- Updated google android library to 4.1.1.4
- Updated support libraries to 24.2.0

### CODE REVIEW

**Comment by jaredsburrows** [comment]
@JakeWharton Starting with support library `24.2.0`, the new min sdk is 9. We can make sure we are not using an methods that are API 8 and override this or bump butterknife to min sdk 9.

**Comment by ChristianBecker** [comment]
Do we really need the complete `support-v4` or can we depend on a support-split directly?

**Comment by jaredsburrows** [comment]
@ChristianBecker It is only used if the developer has it in their dependencies. See the `provided` configuration here: https://github.com/JakeWharton/butterknife/blob/master/butterknife/build.gradle#L23.

**Comment by JakeWharton** [comment]
We only need support-compat. Planning to fix it later.

**Comment by jaredsburrows** [comment]
@ChristianBecker @JakeWharton I can change it to `support-compat`.

**Pull request merged**
