### PR TITLE
Update various dependencies

### PR DESCRIPTION
**Pull request by jaredsburrows**
@JakeWharton 
- Update support libraries to 26.0.1
- Update android gradle plugin to 3.0.0-beta2
- Update lint to 3.0.0-beta2
- Make sure to use latest butterknife release, 8.8.1
- Update robolectric to 3.4.2

### CODE REVIEW

**Comment by jaredsburrows** [comment]
@JakeWharton Merge?

**Comment by jrodbx** [comment]
@jaredsburrows try rebasing on latest?

**Comment by jaredsburrows** [comment]
Will do.

**Comment by jaredsburrows** [comment]
@jrodbx @JakeWharton Done!

**Pull request merged**
