### PR TITLE
Update TravisCI caching

### PR DESCRIPTION
**Pull request by jaredsburrows**
@JakeWharton 
According to the docs here: https://docs.travis-ci.com/user/languages/android/#Caching

### CODE REVIEW

**Comment by jaredsburrows** [comment]
@JakeWharton  merge?

**Comment by jrodbx** [comment]
@jaredsburrows try rebasing on latest?

**Comment by jaredsburrows** [comment]
Will do.

**Comment by jaredsburrows** [comment]
@jrodbx @JakeWharton Done!

**Comment by jaredsburrows** [comment]
@JakeWharton Good to merge?

**Comment by JakeWharton** [comment]
I haven't reviewed it yet, or I would have merged or commented.

**Pull request merged**
