### PR TITLE
Add action and setter methods that take single view

### PR DESCRIPTION
**Pull request by Orbar**
This extends the concept of `Action` and `Setter` and make them available to single views while maintaining the same interface for actual action

### CODE REVIEW

**Comment by JakeWharton** [comment]
Why waste the list and loop instead of just calling the action or setter
directly with the one view?

**Comment by Orbar** [comment]
The intention was to not waste the `index`, but with one view it's meaningless anyway

**Comment by JakeWharton** [comment]
```
butterknife/src/main/java/butterknife/ButterKnife.java:12:8: Unused import - java.util.ArrayList.
butterknife/src/main/java/butterknife/ButterKnife.java:400: Line is longer than 100 characters.
```

**Comment by JakeWharton** [comment]
Squashed and merged. Thanks!

**Pull request closed without merging**
