### PR TITLE
optimization for function findViewById

### PR DESCRIPTION
**Pull request by stormagain**
If findViewByld is called with high frequency, there is a overhead of recursions. Let's make it faster. Update includes new implementation of findViewById with Map used for memoization for previous search result.

### CODE REVIEW

**Comment by JakeWharton** [comment]
What problem is this solving?

**Comment by stormagain** [comment]
Total time consumption，when we have too many views need find out.

**Comment by JakeWharton** [comment]
How are you measuring? Systrace? What's the depth of the hierarchy and how many views are you looking up, for example?

I'm really hesitant about adding something like this without knowing more.

**Comment by stormagain** [comment]
Thank you for reminding, I have maked some ABTest on my devices locally, there is no difference between the two ways. next time I'll do the test first，sorry to disturb.

**Pull request closed without merging**
