### PR TITLE
Change OnPageChange to use add/removeOnPageChangeListener

### PR DESCRIPTION
**Pull request by ChristianBecker**
`ViewPager#setOnPageChangeListener` was deprecated and replaced by `ViewPager#addOnPageChangeListener` and `ViewPager#removeOnPageChangeListener`.

To work-around a test failure (see #398) I had to add a stub of `ViewPager.java`. Additionally I dropped the test dependency on `support-v4` and replaced the remaining `Fragment` usages with `Activity`.

### CODE REVIEW

**Comment by JakeWharton** [comment]
Needs a rebase on your "this" PR.

**Comment by ChristianBecker** [comment]
Rebased.

**Comment by JakeWharton** [comment]
Thansk!

**Comment by JakeWharton** [comment]
Also, thanks!

**Pull request merged**
