### PR TITLE
Split the compiler and runtime into separate artifacts.

### PR DESCRIPTION
**Pull request by riotopsys**

### CODE REVIEW

**Comment by JakeWharton** [comment]
I see this. Will look soon!

**Comment by riotopsys** [comment]
@JakeWharton is there anything I can provide or alter to help you evaluate this PR?

**Comment by JakeWharton** [comment]
Waiting for v7 for this. In general, though there's a bunch of code formatting problems. For example, the project is all two-space indented and most of your changes are all four spaces.

**Comment by JakeWharton** [comment]
This happened!

**Pull request closed without merging**
